import './global.css';
import LenisProvider from '@/components/LenisProvider';

export const metadata = {
  title: 'Welcome to acm-web',
  description: 'Generated by create-nx-workspace custom configurations enhance by Adnan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  )
}
